app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});





// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register/', 'Auth\AuthController@getRegister');
Route::post('auth/register/', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

// Github Login routes...
Route::get('auth/github', 'Auth\AuthController@login');
Route::get('auth/github/callback', 'Auth\AuthController@loginCallback');


// OAuth Github Login rotes..
Route::get('github/authorize', 'Auth\GithubController@githubAuthorize');

Route::get('github/login', 'Auth\GithubController@githubLogin');

// OAuth Facebook Login rotes..
Route::get('facebook/authorize', function(){
    return OAuth::authorize('facebook');
});

Route::get('facebook/login', function(){
    OAuth::login('facebook');
    return view('admin/home/index');
});

Route::get('sitio', function() {
    return view('website/home');
});
Route::get('website', 'Admin\WebsiteController@index');
Route::get('article', 'Admin\WebsiteController@getArticle');
Route::get('categories/{name}', [
   'uses' => 'Admin\WebsiteController@searchCategory',
    'as' => 'website.search.category'
]);

Route::get('tags/{name}', [
    'uses' => 'Admin\WebsiteController@searchTag',
    'as' => 'website.search.tag'
]);


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){

    Route::get('home','Admin\HomeController@index');
    Route::resource( 'users', 'Admin\UsersController');
    Route::resource('categories','Admin\CategoriesController');
    Route::resource('blog','Admin\BlogController');
    Route::resource('profile','Admin\ProfileController');
    Route::resource('resume', 'Admin\ResumeController');
    Route::resource('tags', 'Admin\TagsController');
    Route::resource('resume', 'Admin\CvController');
    Route::resource('images', 'Admin\ImageController');
    Route::resource('portfolio', 'Admin\PortfolioController');
    Route::resource('settings', 'Admin\SettingsController');




});

Route::group(['prefix' => 'register'], function(){
    Route::resource( 'newuser', 'Auth\AuthController');
    Route::get('register/confirmation/{token}', 'Auth\AuthController@store');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Auth\Authenticatable;
use Illuminate\Foundation\Auth\Access\Authorizable;

class Category extends Model
{
    protected $table = 'categories';

    protected $fillable = ['name'];

    public function scopeSearch($query, $name)
    {
        return $query->where('name', 'LIKE', "%$name%");
    }

    public function scopeSearchCategory($query, $name )
    {
        return $query->where('name', 'LIKE', "%$name%");
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;

use Illuminate\Http\Request;


use App\Http\Requests;
use App\Http\Controllers\Controller;
use Laracasts\Flash\Flash;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function __construct(Request $request)
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $categories = Category::search($request->name)->orderBy('id', 'ASC')->paginate('15');
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\CreateCategoriesRequest $request)
    {
        $categories = new Category($request->all());
        $categories->save();
        return redirect ('admin/categories');
        Flash::success('Categoria Creada con Exito');
        //dd($categories);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::findOrFail($id);

        return view('admin.categories.edit', compact('categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\EditCategoriesRequest $request, $id)
    {
        $categories = Category::findOrFail($id);
        //dd($categories);
        $categories->fill($request->all());
        $categories->save();
        return redirect('admin/categories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categories = Category::find($id);
        $categories->delete();

        return redirect('admin/categories');
        Flash::error('Categoria Borrada Exitosamente');
    }
}

resources/views/admin/categories/create.blade.php
@extends('skeleton')


@section('head')
    @include('components.head')
@stop

@section('top')
    @include('components.top')
@stop

@section('contenido')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Welcome</h2>

                @include('admin.categories.components.errors')

                <div class="panel panel-default">
                    <div class="panel-heading">
                        Categorias
                    </div>

                    <div class="panel-body">
                        <p>
                            <a href="{{ route('admin.users.index')}}" class="btn btn-info" role="button">Volver</a>
                        </p>
                        <hr>
                        {!! Form::open(['route' => 'admin.categories.store', 'method' => 'POST']) !!}

                        @include('admin.users.components.errors')

                        @include('admin.categories.components.form-create')

                        <div class="form-group">
                            {!! Form::submit('Crear',array('class' => 'btn btn-info btn-lg'))!!}
                        </div>




                        {!! Form::close() !!}


                    </div>
                </div>

            </div>
        </div>
    </div>

@stop


@section('scripts')
    @include('components.scripts')
@stop

resources/views/admin/categories/edit.blade.php
@extends('skeleton')


@section('head')
    @include('components.head')
@stop

@section('top')
    @include('components.top')
@stop

@section('contenido')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Welcome</h2>



                <div class="panel panel-default">
                    <div class="panel-heading">
                        Categorias
                    </div>

                    <div class="panel-body">
                        <p>
                            <a href="{{ route('admin.users.index')}}" class="btn btn-info" role="button">Volver</a>
                            @include('admin.categories.components.delete')
                        </p>
                        <hr>
                        {!! Form::open(['route' => ['admin.categories.update', $categories->id], 'method' => 'PUT']) !!}

                        @include('admin.categories.components.errors')

                        @include('admin.categories.components.form-edit')

                        <div class="form-group">
                            {!! Form::submit('Actualizar',array('class' => 'btn btn-info btn-lg'))!!}
                        </div>




                        {!! Form::close() !!}


                    </div>
                </div>

            </div>
        </div>
    </div>

@stop


@section('scripts')
    @include('components.scripts')
@stop

resources/views/admin/categories/index.blade.php
@extends('skeleton')

@section('head')
    @include('components.head')
@endsection



@section('top')
    @include('components.top')
@stop

@section('message')
    @include('flash::message')
@stop

@section('buscar')
    @include('components.categoriessearch')
@stop


@section('contenido')

    <div class="modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&close;</button>
                    <h4 class="modal-title">Modal title</h4>
                </div>
                <div class="modal-body">
                    {!! Form::open(['route' => 'admin.categories.store', 'method' => 'POST']) !!}

                    @include('admin.users.components.errors')

                    @include('admin.categories.components.form-create')




                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save Category</button>

                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>

        <!--Start Test Categories -->



@include('admin.categories.components.table')

@endsection

@section('scripts')
    @include('components.scripts')
@endsection