app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});





// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register/', 'Auth\AuthController@getRegister');
Route::post('auth/register/', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

// Github Login routes...
Route::get('auth/github', 'Auth\AuthController@login');
Route::get('auth/github/callback', 'Auth\AuthController@loginCallback');


// OAuth Github Login rotes..
Route::get('github/authorize', 'Auth\GithubController@githubAuthorize');

Route::get('github/login', 'Auth\GithubController@githubLogin');

// OAuth Facebook Login rotes..
Route::get('facebook/authorize', function(){
    return OAuth::authorize('facebook');
});

Route::get('facebook/login', function(){
    OAuth::login('facebook');
    return view('admin/home/index');
});

Route::get('sitio', function() {
    return view('website/home');
});
Route::get('website', 'Admin\WebsiteController@index');
Route::get('article', 'Admin\WebsiteController@getArticle');
Route::get('categories/{name}', [
   'uses' => 'Admin\WebsiteController@searchCategory',
    'as' => 'website.search.category'
]);

Route::get('tags/{name}', [
    'uses' => 'Admin\WebsiteController@searchTag',
    'as' => 'website.search.tag'
]);


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){

    Route::get('home','Admin\HomeController@index');
    Route::resource( 'users', 'Admin\UsersController');
    Route::resource('categories','Admin\CategoriesController');
    Route::resource('blog','Admin\BlogController');
    Route::resource('profile','Admin\ProfileController');
    Route::resource('resume', 'Admin\ResumeController');
    Route::resource('tags', 'Admin\TagsController');
    Route::resource('resume', 'Admin\CvController');
    Route::resource('images', 'Admin\ImageController');
    Route::resource('portfolio', 'Admin\PortfolioController');
    Route::resource('settings', 'Admin\SettingsController');




});

Route::group(['prefix' => 'register'], function(){
    Route::resource( 'newuser', 'Auth\AuthController');
    Route::get('register/confirmation/{token}', 'Auth\AuthController@store');
});

app/Tags.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tags extends Model
{
    protected $table = 'tags';
    protected $fillable = ['name'];

    public function articles()
    {
        return $this->belongsTo('App\Blog')->withTimestamps();
    }

    public function portfolio()
    {
        return $this->belongsTo('App\Porfolio')->withTimestamps();
    }

    public function scopeSearch($query, $name)
    {
        return $query->where('name', 'LIKE', "%$name%");
    }

    public function scopeSearchTag($query, $name )
    {
        return $query->where('name', 'LIKE', "%$name%");
    }
}

app/Http/Controllers/Admin/TagsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Tags;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Laracasts\Flash\Flash;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $tags = Tags::search($request->name)->orderBy('id', 'ASC')
            ->paginate('15');
        return view('admin.tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\CreateTagsRequest $request)
    {
        $tags = new Tags($request->all());
        $tags->save();
        return redirect('admin/tags');
        Flash::success('Tags Creado con Exito!');
        //dd($tags);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tags = Tags::findOrFail($id);
        return view('admin.tags.edit', compact('tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\EditTagsRequets $request, $id)
    {
        $tags = Tags::findOrFail($id);
        $tags->fill($request->all());
        $tags->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tags  = Tags::find($id);
        $tags->delete();
        Flash::error('Tag Borrado Correctamente');
        return redirect('admin/tags');
        //dd($id);
    }
}

resources/views/admin/tags/create.blade.php
@extends('skeleton')

@section('head')
    @include('components.head')
@endsection



@section('top')
    @include('components.top')
@stop

@section('messages')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-dismissible alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&close;</button>
                    <strong>Oh snap!</strong> <a href="#" class="alert-link">Change a few things up</a> and try submitting again.
                    @include('components.errors')
                </div>
            </div>
        </div>
    </div>
@stop


@section('contenido')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Crear Tags
                    </div>
                    <div class="panel-body">
                        <p>
                            <a href="{{ route('admin.tags.index')}}" class="btn btn-info" role="button">Volver</a>
                        </p>
                        {!! Form::open(['route' => 'admin.tags.store', 'method' => 'POST']) !!}

                        <div class="form-group">
                            {!! Form::label('name', 'Nombre') !!}
                            {!! Form::text('name', null, array(
                            'class' => 'form-control',
                            'placeholder' => 'Ingresa El Nombre de el Tag'
                            )) !!}
                        </div>

                        <form-group>
                            {!! Form::submit('Crear Tag', array(
                            'class' => 'btn btn-success'
                            )) !!}
                        </form-group>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>



@endsection



@section('scrtips')
    @include('components.scripts')
@endsection

resources/views/admin/tags/edit.blade.php
@extends('skeleton')

@section('head')
    @include('components.head')
@endsection



@section('top')
    @include('components.top')
@stop

@section('messages')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-dismissible alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&close;</button>
                    @include('components.errors')
                </div>
            </div>
        </div>
    </div>
@stop


@section('contenido')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Crear Tags
                    </div>
                    <div class="panel-body">
                        <p>
                            <a href="{{ route('admin.tags.index')}}" class="btn btn-info" role="button">Volver</a>
                            @include('admin.tags.components.borrar')
                        </p>
                        {!! Form::open(['route' => 'admin.tags.store', 'method' => 'POST']) !!}

                        <div class="form-group">
                            {!! Form::label('name', 'Nombre') !!}
                            {!! Form::text('name', $tags->name, array(
                            'class' => 'form-control',
                            'placeholder' => 'Ingresa El Nombre de el Tag'
                            )) !!}
                        </div>

                        <form-group>
                            {!! Form::submit('Crear Tag', array(
                            'class' => 'btn btn-success'
                            )) !!}
                        </form-group>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>



@endsection



@section('scrtips')
    @include('components.scripts')
@endsection

resources/views/admin/tags/index.blade.php
@extends('skeleton')

@section('head')
    @include('components.head')
@endsection



@section('top')
    @include('components.top')
@stop

@section('messages')
    @include('components.errors')
    @include('flash::message')
@stop

@section('buscar')
    @include('components.search')
@stop

@section('contenido')
   <div class="container">
       <div class="row">
           <div class="col-md-12">
               <a href="{{url('admin/tags/create')}}" class="btn btn-info">Crear Tag</a>
               <hr>
               <div class="panel panel-info">
                   <div class="panel-heading">
                       Tags
                   </div>
                   <div class="panel-body">
                       <table class="table table-hover">
                           <tr>
                               <th>#</th>
                               <th>Nombre de el Tag</th>
                               <th>Creado</th>
                               <th>Editado</th>
                               <th>Acciones</th>
                           </tr>
                           @foreach($tags as $tag)
                           <tr>
                                <td>{{$tag->id}}</td>
                               <td>{{$tag->name}}</td>
                               <td>{{$tag->created_at}}</td>
                               <td>{{$tag->updated_at}}</td>
                                   <td>
                                       <a class="btn btn-warning" href="{{ route ('admin.tags.edit', $tag->id)}}">
                                           <i class="glyphicon glyphicon-eye-open"></i>
                                       </a>
                                       <a class="btn btn-warning" href="">
                                           <i class="glyphicon glyphicon-edit"></i>
                                       </a>
                                       <a class="btn btn-warning btn-delete-user" id="borrar" href="{{ route('admin.tags.destroy', $tag->id )}}"><i class="fa fa-trash"></i></a>
                                   </td>

                           </tr>
                           @endforeach
                       </table>
                   </div>

               </div>
               {!! $tags->render() !!}
           </div>
       </div>
   </div>



@endsection



@section('scrtips')
    @include('components.scripts')
@endsection